### ISSUE TITLE
Discrepancy between Total_Demand.csv and demand-per-building with Output results

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/cea-toolbox-for-arcgis-manual#3]
While organizing the output values for the Total_Demand.csv, I realized there is a bit of discrepancy between what is in the .CSV file and the Documentation Glossary. Here is what I found so far:

1. `Trww0_C` exists in the documentation `under Scenario Outputs>Data>Peak Values`, but it's not in the output of the `Total_Demand.csv` .

2. In the same section of the documentation (under Others) the value Vw0_m3 exists as the total fresh water consumption (cold + hot), while in the output I have `Vw_m3yr,Vww0_m3,Vww_m3yr`, so should the output value `Vw_m3yr` become `Vw0_m3yr`?

3. The values `Vww0_m3,Vww_m3yr` are not described anywhere in the glossary Data outputs.

4. The following values are in the documentation but not in the Total_Demand.csv file `Eauxf0_kWh,Edataf0_kWh,Epro0_kW,Ef0_kW,Qcdataf0_kW,Qcref0_kW,Qcs0_kW,QCf0_kW,Qhs0_kW,Qww0_kW,QHf0_kW`

5. `Qhprof_MWhyr` is one of the outputs, but it is not in the documentation. What is the description in this point?

6. `Aroof_m2,GFA_m2,occ_pax` are not mentioned in the Yearly Values, only `occ_pax` is mentioned in the Hourly Values.

In terms of the Demand Outputs per building, here are my notes:

7. Why aren’t the floor area part of the outputs?

8. `hprof_kWh,Qww_tankloss_kWh,Ecaf_kWh,Tww_tank_C,Tsref_C,Trref_C,Tsdata_C,Trdata_C,mcpref_kWC,mcpdata_kWC` are outputs in the `.csv` file but not in the documentation under `Hourly Values`. Can someone add their description?

**Comment by amraladdin** [comment]
So just as an update, we will use the outputs from the demand as the reference, and update the documentation accordingly.

**Comment by amraladdin** [comment]
@JIMENOFONSECA , can you check points no. 2, 3, 5, 7 & 8 above and give me an answer?

I fixed the rest in the documentation.

**Comment by JIMENOFONSECA** [comment]
In the same section of the documentation (under Others) the value Vw0_m3 exists as the total fresh water consumption (cold + hot), while in the output I have Vw_m3yr,Vww0_m3,Vww_m3yr, so should the output value Vw_m3yr become Vw0_m3yr?

The values Vww0_m3,Vww_m3yr are not described anywhere in the glossary Data outputs.

The following values are in the documentation but not in the Total_Demand.csv file Eauxf0_kWh,Edataf0_kWh,Epro0_kW,Ef0_kW,Qcdataf0_kW,Qcref0_kW,Qcs0_kW,QCf0_kW,Qhs0_kW,Qww0_kW,QHf0_kW

Qhprof_MWhyr is one of the outputs, but it is not in the documentation. What is the description in this point?
**- final demand of process heat **

Aroof_m2,GFA_m2,occ_pax are not mentioned in the Yearly Values, only occ_pax is mentioned in the Hourly Values.
**- you can go ahead and add them to the documentation. Roof area, gross floor area, occupancy**

Why aren’t the floor area part of the outputs?

**- there was no need, if necessary, a new issue should be created **

Qhprof_kWh,Qww_tankloss_kWh,Ecaf_kWh,Tww_tank_C,Tsref_C,Trref_C,Tsdata_C,Trdata_C,mcpref_kWC,mcpdata_kWC are outputs in the .csv file but not in the documentation under Hourly Values. Can someone add their description?

Qhprof_kWh = hourly process heat
Qww_tankloss_kWh = i took this out from the results as it was confusing.
Ecaf_kWh, = electricity consumption due to compressed air
Tww_tank_C = i took this out from the results as it was confusing.
Tsref_C  = temperature of supply of refrigeration services
Trref_C,  = temperature of return of refrigeration services
Tsdata_C,  = temperature of supply of servers cooling
Trdata_C,  = temperature of return of servers cooling
mcpref_kWC = capacity mass flow rate of refrigeration services
mcpdata_kWC = capacity mass flow rate of servers cooling

**Comment by amraladdin** [comment]
`In the same section of the documentation (under Others) the value Vw0_m3 exists as the total fresh water consumption (cold + hot), while in the output I have Vw_m3yr,Vww0_m3,Vww_m3yr, so should the output value Vw_m3yr become Vw0_m3yr?

coudl you show me this one?`

I changed it to Vww0_m3
